#!/bin/bash
#
# submit MOABvESMF profiling jobs from 36 - 4608 cores
#

# escape characters in datadir are required for sed later on
ROOTDIR=/glade/work/rokuingh/MOABperformance/redist
EXDIR=/glade/work/rokuingh/sandbox/profiling/Moab/redist
DATADIR=$EXDIR/data
GRID1=$DATADIR/ll1280x1280_grid.esmf.nc

# create rundir
RUNDIR=$(python run_id.py $ROOTDIR 2>&1)
mkdir $RUNDIR
cd $RUNDIR

bench_procs=(36 72 144 288 576 1152 2304 4608)
# bench_procs=(36 72 144)

for pnum in "${bench_procs[@]}"
do
  cd $RUNDIR
  mkdir $pnum
  cd $pnum
  nnum=$(( $pnum/36 ))
  sed "s&%np%&$pnum&g; s&%nn%&$nnum&g; s&%grid1%&$GRID1&g" $EXDIR/MOAB_eval_run_pbs > MOAB_eval_run_pbs
  cp $EXDIR/MOAB_eval_redist .
  qsub MOAB_eval_run_pbs
done

# cd $RUNDIR
# for pnum in "${bench_procs[@]}"
# do
#   python ../../collect_timing_reports.py "$pnum"
#   python ../../collect_memory_reports.py "$pnum"
# done
