#!/bin/bash
#
#BSUB -J ESMPyRegrid%np%
#BSUB -P P35071400
#BSUB -W 01:00
#BSUB -q regular
#BSUB -n %np%
#BSUB -R "span[ptile=4]"
#BSUB -o ESMPyRegrid%np%.out
#BSUB -e ESMPyRegrid%np%.err
#BSUB -N


module load python all-python-libs
export PYTHONPATH="/glade/u/home/rokuingh/esmf/src/addon/ESMPy/src:$PYTHONPATH"

# regrid method: BILINEAR=0, PATCH=1, CONSERVE=2, NEAREST_STOD=3, NEAREST_DTOS=4
export REGRIDMETHOD=0

mpirun.lsf python regrid.py $REGRIDMETHOD || exit 1